name: CI/CD with GCC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install -y g++
#      run: sudo apt-get install -y g++ clang-tidy

#    - name: Run Clang-Tidy
#      run: clang-tidy main.cpp --config-file=.clang-tidy -- -std=c++17

    - name: Build
      run: g++ main.cpp -o my_program

 #   - name: Test
 #     run: ./my_program

    - name: Zip the executable
      run: zip setup.zip my_program

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: setup-zip
        path: ./setup.zip

    #- name: Run the tests
    #  run: ./tests && echo "All tests passed!"

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: setup-zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SUPERSECRET }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: "Release v1.0.${{ github.run_number }}"
        draft: false
        prerelease: false
